version: "3.9"
services:
  centre-iam:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8190:8190"
    networks:
      - starxus-network

networks:
  starxus-network:
    external: true